[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd backend && npm install --legacy-peer-deps']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd backend && npm start'